config/routes.rb
Rails.application.routes.draw do

  root 'requests#index'
  resources :requests, except: [:show]

end

app/models/dept.rb
class Dept < ActiveRecord::Base

  has_many :requests, dependent: :nullify

  validates :name, presence: true, length: { minimum: 3 }

end

app/models/request.rb
class Request < ActiveRecord::Base

  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :dept
  
  validates :name, :email, presence: :true
  validates :done, default: false, null: false
  
  before_create :set_blah

  # set per_page globally
  WillPaginate.per_page = 5

  def self.search(query)
    where("name LIKE ? OR email LIKE ? OR msg LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end

  def self.req_lists_order
    Request.all.order("done ASC")
  end

  private

  def set_blah
    if done.nil? 
      self.done = false
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_request, only: [:edit, :update, :destroy]

  def new
    @dept = Dept.first
    @req = @dept.requests.new
  end

  def create
    @req = Request.new request_params
    if @req.save
      redirect_to requests_path
    else
      render :new #render "new.html.erb"
    end
  end

  def edit
    #@req set in before_action
  end

  def update
    #@req set in before_action
    if @req.update request_params
      redirect_to requests_path(search: params[:search])
    else
      render :edit
    end
  end 

  def index
    if params[:search]
      # @req_lists = Request.search(params[:search]).order("created_at DESC")
      @req_lists = Request.search(params[:search]).order("done ASC").paginate(:page => params[:page], per_page: 10)
    else
      @req_lists = Request.req_lists_order.paginate(:page => params[:page], per_page: 10)
    end
  end

  def destroy
    #@req set in before_action
    @req.destroy
    redirect_to requests_path, notice: "Request destroyed successfully!"
  end

  private

  def find_request
    @req = Request.friendly.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:name, :email, :dept_id, :msg, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Support</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar">
      <div class="container">
        <%=link_to "New Request", new_request_path %> | 
        <%=link_to "Request Index", requests_path %>
      </div>
    </div>

    <div class="container" style="padding-top:50px;">
      <!-- flash notice and alert for gem 'devise' usage -->
      <%#= flash[:notice] || flash[:alert] %>
      <% flash.each do |name, msg| %>
        <% if name=="notice" %>
                <%= content_tag :div, msg, class: "alert alert-info", role: "alert" %>
        <% elsif name=="alert" %>
                <%= content_tag :div, msg, class: "alert alert-warning", role: "alert" %>
        <% elsif name=="error" %>
                <%= content_tag :div, msg, class: "alert alert-danger", role: "alert" %>
        <% else %>
                <%= content_tag :div, msg, class: "alert alert-info", role: "alert" %>
        <% end %>
      <% end %>

      <%= yield %>
    
    </div>
  </body>
</html>

app/views/requests/_form.html.erb
<!--
# <%= form_for @req do |f| %>
#   <div class: "form-group">
#   <%= f.label "Name" %>
#   <%= f.text_field :name, class: "form-control" %>
#   </div>
#   <div class: "form-group">
#   <%= f.label :email %>
#   <%= f.text_field :email, class: "form-control" %>
#   </div>
#   <div class: "form-group">
#   <%= f.label :dept %>
#   <%#= f.collection_check_boxes :dept_ids, Dept.all, :id, :name %>
#   </div>
#   <div class: "form-group">
#   <%= f.label :msg %>
#   <%= f.text_area :msg, class: "form-control" %>
#   </div>
#   <p></p>
#   <%= f.submit %>
# <% end %>
-->

<%= simple_form_for @req, html: {class: "form-horizontal"} do |f| %>
  <%= f.input :name, inline_label: "Name", placeholder: "input your name here" %>
  <%= f.input :email %>
  <div class="inline-class">
  <%= f.association :dept, as: :radio_buttons, label: "Department" %>
  </div>
  <%= f.input :msg, label: "Message", placeholder: "input your request message here" %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/requests/edit.html.erb
<h1>Edit Request</h1>

<%= render "form" %>

app/views/requests/index.html.erb
<div class="col-md-12 heading-wrapper">
  <div class="heading col-md-7">
    <h1>Support Requests</h1>
  </div>
  <div class="search-bar col-md-5">
    <%= form_tag(requests_path, :method => "get", id: "search-form", class: "pull-right") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Requests" %>
      <%= submit_tag "Search", :name => nil %>
    <% end %>
  </div>
</div>

<table class="table table-striped table-bordered table-hover table-responsive">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Department</th>
    <th>Message</th>
    <th class="action-column">Actions</th>
  </tr>
  <% @req_lists.each do |q| %>
    <tr>
      <td><%= q.name %></td>
      <td><a href="mailto:<%= q.email %>"><%= q.email %></td>
      <td>
        <% if q.dept != nil %>
          <%= q.dept.name %>
        <% end %>
      </td>
      <td><%= q.msg %></td>
      <td><%= link_to "Edit", edit_request_path(q), method: :get, class: "btn btn-info btn-xs"%> |
          <%= link_to "Delete", request_path(q), method: :delete, class: "btn btn-danger btn-xs" %> |

          <% if q.done? %>
            <%= link_to "done", request_path(q, search: params[:search], 
              request: { done: false }), method: :patch, class: "btn btn-success btn-xs" %>
          <% else %>
            <%= link_to "undone", request_path(q, search: params[:search],
              request: { done: true }), method: :patch, class: "btn btn-warning btn-xs" %>
          <% end %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate @req_lists %>

app/views/requests/new.html.erb
<h1>Create New Request</h1>

<%= render "form" %>